image: Visual Studio 2019
skip_commits:
  message: /docs|Merge pull request.*/
build_script:
- pwsh: |
    Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
    ./dotnet-install.ps1 -JSonFile global.json -Architecture x64 -InstallDir 'C:\Program Files\dotnet'
    dotnet build --configuration Release
    dotnet test --configuration Release --no-build --no-restore --filter Category!=Integration
test: off
artifacts:
- path: nugets\**\*.nupkg